version: "3"
services:
  stories:
    build: .
    # volumes allow data to persist even if the container is shut down
    volumes:
      - stories:/app/story
    ports:
      - 80:3000
volumes:
  stories: 