apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pv
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce      
  storageClassname: standard
  resources: 
    requests:
      storage: 1Gi