apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    # the value of story is taken from deployment.yaml file
    app: story
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000